In [1]:
import pandas as pd

# Load matches dataset
matches = pd.read_csv("cleaned_matches.csv")

# Clean column names
matches.columns = matches.columns.str.strip().str.lower()


# 🏆 1. Matches won per season
season_wins = matches.groupby(["season", "winner"]).size().reset_index(name="wins")
season_wins = season_wins.sort_values(["season", "wins"], ascending=[True, False])

print("✅ Matches Won by Teams in Each Season")
display(season_wins.head(20))  # preview first few seasons


# 🏆 2. Final Winners (Champion of Each Season)
final_matches = matches.sort_values("date").groupby("season").tail(1)

final_winners = final_matches[["season", "winner"]].reset_index(drop=True)

print("\n✅ IPL Final Winners by Season")
display(final_winners)


# 🏆 3. Total Championships (Titles per Team)
titles_count = final_winners["winner"].value_counts().reset_index()
titles_count.columns = ["team", "titles"]

print("\n✅ Total IPL Titles per Team")
display(titles_count)

✅ Matches Won by Teams in Each Season

    season                       winner  wins
5     2008             Rajasthan Royals    13
4     2008                 Punjab Kings    10
0     2008          Chennai Super Kings     9
1     2008               Delhi Capitals     7
3     2008               Mumbai Indians     7
2     2008        Kolkata Knight Riders     6
6     2008  Royal Challengers Bangalore     4
7     2008          Sunrisers Hyderabad     2
9     2009               Delhi Capitals    10
14    2009  Royal Challengers Bangalore     9
15    2009          Sunrisers Hyderabad     9
8     2009          Chennai Super Kings     8
12    2009                 Punjab Kings     7
13    2009             Rajasthan Royals     6
11    2009               Mumbai Indians     5
10    2009        Kolkata Knight Riders     3
19    2010               Mumbai Indians    11
16    2010          Chennai Super Kings     9
22    2010  Royal Challengers Bangalore     8
23    2010          Sunrisers Hyderabad     8

✅ IPL Final Winners by Season

    season                 winner
0     2009    Chennai Super Kings
1     2011  Kolkata Knight Riders
2     2012  Kolkata Knight Riders
3     2013    Chennai Super Kings
4     2015  Kolkata Knight Riders
5     2016    Sunrisers Hyderabad
6     2017           Punjab Kings
7     2018    Chennai Super Kings
8     2014           Punjab Kings
9     2021    Chennai Super Kings
10    2010         Delhi Capitals
11    2019    Chennai Super Kings
12    2022   Lucknow Super Giants
13    2023         Gujarat Titans
14    2024         Delhi Capitals
15    2008    Chennai Super Kings
16    2020    Sunrisers Hyderabad

✅ Total IPL Titles per Team

                    team  titles
0    Chennai Super Kings       6
1  Kolkata Knight Riders       3
2    Sunrisers Hyderabad       2
3           Punjab Kings       2
4         Delhi Capitals       2
5   Lucknow Super Giants       1
6         Gujarat Titans       1